name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov

      - name: Run tests
        run: |
          pytest test_username_generator.py
          pytest --cov=username_generator --cov-report=xml
  sonar_analysis:
      runs-on: ubuntu-latest
      needs: test

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Install tox and any other packages
          run: pip install tox
        - name: Run tox
          run: tox -e py

        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@v2
          with:
            args: >
              -Dproject.settings=sonar-project.properties
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build_and_push:
    runs-on: ubuntu-latest
    needs:
      - test
      - sonar_analysis      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/username-generator:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/username-generator:latest
      
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/username-generator:latest
          severity: CRITICAL
          ignore-unfixed: false

