name: Python CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Vérifier le code source depuis GitHub
      - name: Checkout code
        uses: actions/checkout@v3
      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      # Étape 4 : Exécuter les tests unitaires
      - name: Run tests
        run: |
          pytest test_username_generator.py